export {default as Logo} from './logo.svg'
export {default as project} from './project.svg'
export {default as bsc} from './bsc.png'
export {default as logodown} from './logodown.svg'
export {default as part1} from './part1.svg'
export {default as part2} from './part2.svg'
export {default as part3} from './part3.svg'
export {default as part4} from './part4.svg'
export {default as part5} from './part5.svg'
export {default as part6} from './part6.svg'
export {default as part7} from './part7.svg'
export {default as news} from './news.svg'
export {default as eth} from './eth.webp'
export {default as bnb} from './bnb.png'
export {default as bnbb} from './bnb1.png'

